var stocks = [
{"symbol":"III","name":"3i Group Plc"},
{"symbol":"ADM","name":"Admiral Group"},
{"symbol":"AAL","name":"Anglo American"},
{"symbol":"ANTO","name":"Antofagasta plc"},
{"symbol":"AHT","name":"Ashtead Group plc"},
{"symbol":"ABF","name":"Associated British Foods plc"},
{"symbol":"AGR","name":"Assura plc"},
{"symbol":"AML","name":"Aston Martin Lagonda"},
{"symbol":"AZN","name":"AstraZeneca plc"},
{"symbol":"AUTO","name":"Auto Trader Group plc"},
{"symbol":"AVST","name":"Avast plc"},
{"symbol":"AVV","name":"AVEVA Group plc"},
{"symbol":"AV.","name":"Aviva plc"},
{"symbol":"AVON","name":"Avon Rubber plc"},
{"symbol":"BME","name":"B&M European Value Retail SA"},
{"symbol":"BA.","name":"BAE Systems plc"},
{"symbol":"BGEO","name":"Bank Of Georgia Group Plc"},
{"symbol":"BARC","name":"Barclays plc"},
{"symbol":"BDEV","name":"Barratt Developments plc"},
{"symbol":"BWY","name":"Bellway plc"},
{"symbol":"BKG","name":"Berkeley Group Holdings plc"},
{"symbol":"BHP","name":"BHP Group Plc"},
{"symbol":"BP.","name":"BP Plc"},
{"symbol":"BATS","name":"British American Tobacco plc"},
{"symbol":"BLND","name":"British Land Co plc"},
{"symbol":"BT.A","name":"BT Group plc"},
{"symbol":"BNZL","name":"Bunzl plc"},
{"symbol":"BRBY","name":"Burberry Group plc"},
{"symbol":"CPI","name":"Capita plc"},
{"symbol":"CCL","name":"Carnival plc"},
{"symbol":"CEY","name":"Centamin plc"},
{"symbol":"CNA","name":"Centrica plc"},
{"symbol":"CINE","name":"Cineworld Group plc"},
{"symbol":"CBG","name":"Close Brothers Group plc"},
{"symbol":"COA","name":"Coats Group plc"},
{"symbol":"CCH","name":"Coca-Cola HBC AG"},
{"symbol":"CPG","name":"Compass Group plc"},
{"symbol":"CTEC","name":"ConvaTec Group Plc"},
{"symbol":"CRST","name":"Crest Nicholson Holdings plc"},
{"symbol":"CRH","name":"CRH plc"},
{"symbol":"CRDA","name":"Croda International plc"},
{"symbol":"DCC","name":"DCC plc"},
{"symbol":"DPH","name":"Dechra Pharmaceuticals plc"},
{"symbol":"DLN","name":"Derwent London plc"},
{"symbol":"DGE","name":"Diageo plc"},
{"symbol":"DLG","name":"Direct Line Insurance Group plc"},
{"symbol":"DC.","name":"Dixons Carphone plc"},
{"symbol":"DNLM","name":"Dunelm Group Plc"},
{"symbol":"EZJ","name":"easyJet plc"},
{"symbol":"ELM","name":"Elementis plc"},
{"symbol":"ENT","name":"Entain plc"},
{"symbol":"EVR","name":"Evraz plc"},
{"symbol":"EXPN","name":"Experian Plc"},
{"symbol":"FERG","name":"Ferguson plc"},
{"symbol":"FGP","name":"FirstGroup plc"},
{"symbol":"FLTR","name":"Flutter Entertainment"},
{"symbol":"FRES","name":"Fresnillo"},
{"symbol":"FUTR","name":"Future plc"},
{"symbol":"GFS","name":"G4S Plc"},
{"symbol":"GAW","name":"Games Workshop Group"},
{"symbol":"GSK","name":"GlaxoSmithKline plc"},
{"symbol":"GLEN","name":"Glencore plc"},
{"symbol":"GNC","name":"Greencore Group plc"},
{"symbol":"HLMA","name":"Halma plc"},
{"symbol":"HMSO","name":"Hammerson Plc"},
{"symbol":"HBR","name":"Harbour Energy plc"},
{"symbol":"HL.","name":"Hargreaves Lansdown plc"},
{"symbol":"HTWS","name":"Helios Towers plc"},
{"symbol":"HIK","name":"Hikma Pharmaceuticals"},
{"symbol":"HSV","name":"Homeserve plc"},
{"symbol":"HWDN","name":"Howden Joinery Group Plc"},
{"symbol":"HSBA","name":"HSBC Holdings plc"},
{"symbol":"IMB","name":"Imperial Brands Group"},
{"symbol":"INF","name":"Informa plc"},
{"symbol":"IHG","name":"InterContinental Hotels Group plc"},
{"symbol":"ICP","name":"Intermediate Capital Group plc"},
{"symbol":"IAG","name":"International Consolidated Airlines Group SA"},
{"symbol":"ITRK","name":"Intertek Group plc"},
{"symbol":"ITV","name":"ITV plc"},
{"symbol":"IWG","name":"IWG plc"},
{"symbol":"JD.","name":"JD Sports Fashion plc"},
{"symbol":"JMAT","name":"Johnson Matthey Plc"},
{"symbol":"JET","name":"Just Eat Takeaway.com NV"},
{"symbol":"KGF","name":"Kingfisher"},
{"symbol":"LAND","name":"Land Securities Group plc"},
{"symbol":"LGEN","name":"Legal & General Group plc"},
{"symbol":"LLOY","name":"Lloyds Banking Group plc"},
{"symbol":"LSEG","name":"London Stock Exchange Group plc"},
{"symbol":"MNG","name":"M&G plc"},
{"symbol":"MKS","name":"Marks & Spencer Group plc"},
{"symbol":"MARS","name":"Marstons plc"},
{"symbol":"MDC","name":"Mediclinic International plc"},
{"symbol":"MGGT","name":"Meggitt"},
{"symbol":"MRO","name":"Melrose Industries plc"},
{"symbol":"MNDI","name":"Mondi Plc"},
{"symbol":"MRW","name":"Morrison (Wm) Supermarkets"},
{"symbol":"NG.","name":"National Grid"},
{"symbol":"NXT","name":"Next plc"},
{"symbol":"OCDO","name":"Ocado Group plc"},
{"symbol":"PSON","name":"Pearson plc"},
{"symbol":"PNN","name":"Pennon Group"},
{"symbol":"PSN","name":"Persimmon plc"},
{"symbol":"POG","name":"Petropavlovsk plc"},
{"symbol":"PETS","name":"Pets At Home Group PLC"},
{"symbol":"PHNX","name":"Phoenix Group Holdings Plc"},
{"symbol":"PTEC","name":"Playtech plc"},
{"symbol":"PLUS","name":"Plus500 Ltd"},
{"symbol":"POLY","name":"Polymetal International plc"},
{"symbol":"PRU","name":"Prudential plc"},
{"symbol":"RKT","name":"Reckitt Benckiser Group Plc"},
{"symbol":"REL","name":"RELX plc"},
{"symbol":"RTO","name":"Rentokil Initial Plc"},
{"symbol":"RMV","name":"Rightmove plc"},
{"symbol":"RIO","name":"Rio Tinto plc"},
{"symbol":"RR.","name":"Rolls Royce Holdings Plc"},
{"symbol":"RDSA","name":"Royal Dutch Shell Plc A Shares"},
{"symbol":"RSA","name":"RSA Insurance Group"},
{"symbol":"SGE","name":"Sage Group plc"},
{"symbol":"SBRY","name":"Sainsbury (J) plc"},
{"symbol":"SDR","name":"Schroders plc"},
{"symbol":"SMT","name":"Scottish Mortgage Investment Trust plc"},
{"symbol":"SGRO","name":"Segro Plc"},
{"symbol":"SVT","name":"Severn Trent Plc"},
{"symbol":"SHI","name":"Sig plc"},
{"symbol":"SN.","name":"Smith & Nephew plc"},
{"symbol":"SMDS","name":"Smith (DS)"},
{"symbol":"SMIN","name":"Smiths Group Plc"},
{"symbol":"SKG","name":"Smurfit Kappa Group Plc"},
{"symbol":"SPX","name":"Spirax-Sarco Engineering plc"},
{"symbol":"SPT","name":"Spirent Communications plc"},
{"symbol":"SSE","name":"SSE plc"},
{"symbol":"STJ","name":"St James's Place Plc"},
{"symbol":"STAN","name":"Standard Chartered plc"},
{"symbol":"SLA","name":"Standard Life Aberdeen Plc"},
{"symbol":"SYNT","name":"Synthomer plc"},
{"symbol":"TATE","name":"Tate & Lyle plc"},
{"symbol":"TW.","name":"Taylor Wimpey plc"},
{"symbol":"TEP","name":"Telecom Plus plc"},
{"symbol":"TSCO","name":"Tesco plc"},
{"symbol":"BBOX","name":"Tritax Big Box REIT plc"},
{"symbol":"TUI","name":"TUI AG"},
{"symbol":"TLW","name":"Tullow Oil plc"},
{"symbol":"UDG","name":"UDG Healthcare plc"},
{"symbol":"ULVR","name":"Unilever plc"},
{"symbol":"UU.","name":"United Utilities Group Plc"},
{"symbol":"VCT","name":"Victrex"},
{"symbol":"VMUK","name":"Virgin Money UK plc"},
{"symbol":"VOD","name":"Vodafone Group plc"},
{"symbol":"SMWH","name":"WH Smith Plc"},
{"symbol":"WTB","name":"Whitbread plc"},
{"symbol":"WPP","name":"WPP plc"},
{"symbol":"BOO","name":"Boohoo Group plc"},
{"symbol":"CWR","name":"Ceres Power Holdings"},
{"symbol":"CVSG","name":"CVS Group plc"},
{"symbol":"FEVR","name":"Fevertree Drinks plc"},
{"symbol":"OMU","name":"Old Mutual Limited"},
{"symbol":"BNC","name":"Banco Santander"}
]
